//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.LookUps = new HashSet<LookUp>();
        }
    
        public long AppointmentNo { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
    
        public virtual ICollection<LookUp> LookUps { get; set; }
    }
}
