//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.LookUps = new HashSet<LookUp>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Speciality { get; set; }
        public Nullable<long> Fee { get; set; }
        public Nullable<System.TimeSpan> Timming { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Hospital { get; set; }
    
        public virtual ICollection<LookUp> LookUps { get; set; }
    }
}
