//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingList
    {
        public WaitingList()
        {
            this.LookUps = new HashSet<LookUp>();
        }
    
        public long id { get; set; }
        public string Patients { get; set; }
    
        public virtual ICollection<LookUp> LookUps { get; set; }
        public virtual WaitingList WaitingList1 { get; set; }
        public virtual WaitingList WaitingList2 { get; set; }
    }
}
